version: '3'
services:
  database:
    image: postgres:10.5-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aware_v2_test
    expose:
      - "5432"
  api:
    build:
      context: ./
      dockerfile: ./deploy/Dockerfile
    environment:
      - DB_HOST=database
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=aware_v2_test
      - RUN_GOOGLE_CALENDAR_API_EVENTS_WORKER=false
      - RUN_OUTLOOK_CALENDAR_EVENTS_WORKER=false
    depends_on:
      - database